### ISSUE TITLE
Might be a good idea to include `lion-soc` in the `.cabal` file

### ISSUE THREAD

**Issue by LighghtEeloo** [standardsemiconductor/lion#9]
I was trying to build this nice project this morning and found the `soc` executable not working:

```console
<no location info>: error: module `Soc' cannot be found locally
Error when running Shake build system:
  at want, called at app/Main.hs:27:3 in main:Main
* Depends on: _build/Soc.bin
  at need, called at app/Main.hs:78:5 in main:Main
* Depends on: _build/Soc.asc
  at need, called at app/Main.hs:66:5 in main:Main
* Depends on: _build/Soc.json
  at need, called at app/Main.hs:56:5 in main:Main
* Depends on: _build/Soc.topEntity/Soc.v
* Raised the exception:
ExitFailure 1
```

And then I added `lion-soc` to the `build-depends` in all executables of `lion-soc.cabal` and it worked. So I think maybe it would be a good idea to add these to lines.

**Comment by dopamane** [comment]
Thank you for raising this issue. However, I'm not able to reproduce it. I think it might be a cabal issue. What `cabal --version` are you using? I'm using `3.10.1.0`. The `soc` executable should implicitly depend on `lion-soc` library because they are in the same cabal file.

**Comment by LighghtEeloo** [comment]
Thank you for your patience. Here's my setup: I'm using ghcup with ghc `9.0.2`, cabal `3.10.1.0` and stack `2.9.3`.

I'm running `cabal run soc` under `/lion-soc`, and my full compiling experience, from a clean build, goes:

```console
$ cabal run soc
# can't build because modules in lion-soc can't be found

# manually editing .cabal files to add the dependencies...

$ cabal run soc
# builds smoothly

# removing the dependencies from .cabal files again
$ cabal run soc
# still being able to build; I guess it's because of the (potentially global) build cache
```

Therefore, it might be quite reasonable for you to be unable to reproduce. I'm super unsure of how cabal, or the Haskell build toolchain in general, works internally, so at the moment, I'm very confused...

**Comment by LighghtEeloo** [comment]
Nevertheless, this is a great project! I'd like to base my computer architecture course project on Lion following the BSD-3 license. It was a bit frightening to start with Clash, but this project has taught us a lot. My most sincere thanks.

**Comment by dopamane** [comment]
I was able to reproduce the issue. Running `cabal build` before `cabal run soc` resolves the issue. I'll include the build step in the README.
